
#Server port
server:
    port: 8888
 
#Git repo location.
spring:
    cloud:
        config:
            server:
                git:
                    uri: file://C:/project/worksapce_msa/spring-config-server
                    timeout: 4
# Authentication basic                    
#                    username: admin
#                    password: admin
 
#Disable security of the Management endpoint
management:
    security:
        enabled: false